#!/bin/bash
# sort of like svn-update-all

curbranch=`git branch | grep '^\*' | sed -e 's/^\* //'`
if [[ x"$curbranch" == x"" ]]; then
	echo Unable to determine current branch
	exit 1
fi

git commit -a
git push origin "$curbranch"
git pull origin "$curbranch"
git fetch

